# stage_config.yaml
WorldConfig:
  width : 1280
  height : 720
  sync_loads : True
  headless : False
  renderer : RayTracedLighting

# Data load and save path
DataPath:
  PartsPath: /home/pika/assemble_step/
  OutPath: /media/pika/Joyoyo/temp/
  MdlPath: /home/pika/omniverse_mdl/
  # RosPath: 
  # ImagesPath: 
  # GraspPath:

Renderer:
  Simulation_steps: 100
  Render_steps: 6

# Camera Config
Camera:
  num : 5
  focal_length: 66
  focus_distance: 200
  width: 1280
  height: 720


# groundplane Config
GroundPlane:
  prim: /World/GroundPlane
  size: 100
  z_position: 0
  scale:
    - 1
    - 1
    - 1
  PhysicsMaterial:
    prim: /World/groundPlane/PhysicsMaterial
    dynamic_friction: 0.5
    static_friction: 0.5
    restitution: 0.8

# Component Config
Component:
  x_min: -10
  x_max: 10
  y_min: -10
  y_max: 10
  z_min: 5
  z_max: 30

# Randomization Config
Random:
  Camera:
    radius_min: 300
    radius_max: 350
    look_at_min: -10
    look_at_max: 10
    x_min_norm: -0.5
    x_max_norm: 0.5
    y_min_norm: -0.5
    y_max_norm: 0.5
  Light:
    Type: Sphere
    Intensity:
      Mean: 5000
      Delta: 200
    Position:
      x_y_min: -50
      x_y_max: 50
      z_min: 100
      z_max: 150
    Scale:
      min: 100
      max: 200