# stage_config.yaml

WorldConfig:
  width : 1280
  height : 720
  sync_loads : True
  headless : False
  renderer : RayTracedLighting

DataPath:
  PartsPath: /home/pika/Desktop/assemble_step/
  OutPath: /home/pika/Desktop/assemble_step/_output_headless/
  RosPath: 
  ImagesPath: 
  GrapsPath:
Camera:
  num : 3
  focal_length: 38.7
  focus_distance: 400
  width: 1280
  height: 720
num_sim_steps: 10

# groundplane config
GroundPlane:
  prim: /World/GroundPlane
  size: 100
  z_position: 0
  scale:
    - 1
    - 1
    - 1
  PhysicsMaterial:
    prim: /World/groundPlane/PhysicsMaterial
    dynamic_friction: 0.5
    static_friction: 0.5
    restitution: 0.8
  PreviewSurface:
    prim: /World/Looks/Ground_PreviewSurface
    color:
      - 0.5
      - 0.5
      - 0.5
    roughness: 0.4
    metallic: 0.4

Component:
  x_min: -10
  x_max: 10
  y_min: -10
  y_max: 10
  z_min: 5
  z_max: 30
  source: /home/pika/.lcoal/share/ov/pkg/issac_sim-2022.2.1/Component/
  prim: /World/Assemble/
  # position:
  #   - 0
  #   - 0
  #   - 0
  # orientation:
  #   vector: 
  #     - 0
  #     - 1
  #     - 0
  #   theta: 90 
  # scale: 
  #   - 1
  #   - 1
  #   - 1
  # PhysicsMaterial: 
  #   prim: /World/Assemble/Looks/
  #   source:  /home/pika/.lcoal/share/ov/pkg/issac_sim-2022.2.1/Component/Geom/
  # PreviewSurface: 
  #   prim: /World/Assemble/Looks/
  #   source: /home/pika/.lcoal/share/ov/pkg/issac_sim-2022.2.1/Component/Rigid/
